set(NAME_LIB Logging)

add_library(${NAME_LIB} STATIC IMPORTED)
find_library(LOGGING_LIBRARY_PATH ${NAME_LIB} HINTS "${CMAKE_CURRENT_LIST_DIR}/../../")
set_target_properties(${NAME_LIB} PROPERTIES IMPORTED_LOCATION "${LOGGING_LIBRARY_PATH}")